@echo off
rem ============================================================================
rem  git push through an HTTP-CONNECT proxy running in fake-IP mode.
rem
rem  See connect_tunnel.py for the measurements behind this detour. Short version:
rem  port 22 gets a "200 Connection Established" from the proxy and then no SSH
rem  banner, so plain `git push` dies with "Connection closed by <fake ip> port
rem  22". github.com over HTTPS is reachable but push needs a credential that may
rem  not be stored, whereas ssh.github.com:443 is GitHub's official SSH-over-HTTPS
rem  endpoint and does get forwarded.
rem
rem  Usage (run from anywhere; it cd's to the repo root itself):
rem    tools\git-proxy\push.bat                  -> git push origin main
rem    tools\git-proxy\push.bat origin develop   -> git push origin develop
rem    tools\git-proxy\push.bat --tags           -> any git push arguments
rem
rem  Overrides:
rem    PYTHON       python.exe to use (default: first python 3 found on PATH)
rem    TUNNEL_PROXY proxy host:port       (default: https_proxy / http_proxy)
rem
rem  Nothing here is machine specific: the ssh config is generated per run into
rem  %TEMP%, because committing one would mean baking in this checkout's absolute
rem  paths and the local python's.
rem ============================================================================
setlocal

set "HERE=%~dp0"
set "REPO=%~dp0..\.."

rem ---- 1. locate a python 3 ---------------------------------------------------
rem `where python` happily returns a Python 2 or the Microsoft Store stub, and
rem both fail here in confusing ways, so each candidate is actually executed.
set "PY=%PYTHON%"
if defined PY goto :python_ready

set "PY="
for /f "delims=" %%I in ('where python 2^>nul') do (
  if not defined PY (
    "%%I" -c "import sys; sys.exit(0 if sys.version_info[0] == 3 else 1)" >nul 2>nul
    if not errorlevel 1 set "PY=%%I"
  )
)

:python_ready
if not defined PY (
  echo [push] no python 3 found on PATH. Set PYTHON to a python.exe path.
  exit /b 1
)
if not exist "%PY%" (
  echo [push] PYTHON is set to "%PY%", which does not exist.
  exit /b 1
)

rem ---- 2. resolve the proxy --------------------------------------------------
set "PROXY=%TUNNEL_PROXY%"
if not defined PROXY set "PROXY=%https_proxy%"
if not defined PROXY set "PROXY=%http_proxy%"
if not defined PROXY (
  echo [push] no proxy configured. Set TUNNEL_PROXY=host:port ^(e.g. 127.0.0.1:7890^).
  exit /b 1
)
set "PROXY=%PROXY:http://=%"
set "PROXY=%PROXY:https://=%"
set "PROXY=%PROXY:/=%"

rem ---- 3. generate the ssh config --------------------------------------------
rem ssh_config cannot expand environment variables, hence generating the file
rem instead of shipping one. `%%h %%p` is how a batch file emits a literal
rem "%h %p" -- a lone %h would be swallowed as an (undefined) variable.
set "CFG=%TEMP%\rubik_git_proxy_ssh.conf"
set "PYF=%PY:\=/%"
set "TUNF=%HERE%connect_tunnel.py"
set "TUNF=%TUNF:\=/%"

(
  echo # Generated by tools\git-proxy\push.bat -- edits here are overwritten.
  echo Host github.com
  echo     HostName ssh.github.com
  echo     Port 443
  echo     User git
  echo     ProxyCommand "%PYF%" "%TUNF%" %%h %%p
  echo     StrictHostKeyChecking accept-new
) > "%CFG%"

set "GIT_SSH_COMMAND=ssh -F "%CFG%""
set "TUNNEL_PROXY=%PROXY%"

echo [push] python      : %PY%
echo [push] proxy       : %PROXY%
echo [push] ssh config  : %CFG%
echo [push] route       : github.com -> ssh.github.com:443 via CONNECT
echo.

rem ---- 4. push ----------------------------------------------------------------
pushd "%REPO%" || exit /b 1
if "%~1"=="" (
  git push origin main
) else (
  git push %*
)
set "RC=%ERRORLEVEL%"
popd

echo.
if "%RC%"=="0" (
  echo [push] done.
) else (
  echo [push] git push exited with %RC%.
  echo [push] if the failure mentions the host key, the generated config above is
  echo [push] still on disk and can be inspected.
)
endlocal & exit /b %RC%
