import 'dart:convert';
import 'dart:math' as math;
import 'dart:typed_data';

import 'rubik_ffi_bridge.dart';

/// One scrambled state plus the solver results measured on the host (x86_64).
///
/// The facelet string is the input; the three numbers are the reference the
/// phone has to reproduce. They are compared by *length* rather than by exact
/// move string, because both solvers are allowed to return any shortest answer
/// - what must not change across architectures is how long the answer is.
class DeviceVector {
  const DeviceVector(
    this.facelets,
    this.hostKociembaLen,
    this.hostCfopStages,
    this.hostCfopMoves,
  );

  final String facelets;
  final int hostKociembaLen;
  final int hostCfopStages;
  final int hostCfopMoves;
}

// Generated by tools/native_tests/gen_vectors.cpp - do not edit.
// 8 scrambled states with their host (x86_64) solver results.
const List<DeviceVector> kDeviceVectors = <DeviceVector>[
  DeviceVector('LRRUULDUDFFULRRRDBBFRLFDUFDFDBRDBULLFBLRLURULFDDBBFUBB', 21, 9, 77),
  DeviceVector('RDUBUFUDLFUFURFBBRLRDDFLURUFFRBDUDFDDLBRLBLRLRLFUBLBDB', 21, 9, 74),
  DeviceVector('BDBBULLBDFURRRUFFLDURFFBUBRBLUFDLLDFUDBDLRDURDFLRBRULF', 20, 9, 91),
  DeviceVector('BLDFUFRRURDLLRLBBFDUFBFBDLRLUDUDDBRUURFDLUUFFBDLRBFLBR', 20, 8, 76),
  DeviceVector('FDURUDRUUBLBDRLRLUBBRFFFBBULDFUDFDRLDUDULRRLDLRLFBBFBF', 21, 9, 86),
  DeviceVector('RDBUULLBLBFURRUDBFDLURFFLBBFRRUDDUDUDRBLLDFBDRLFUBFLFR', 20, 9, 83),
  DeviceVector('DUULUDUUFUBLBRRLDFBLRRFUDLUBFBRDLDFLFBRFLDBBLFFRRBUDDR', 21, 9, 89),
  DeviceVector('LDURUBUUBLDRDRLDBDRLDDFLRBFDLLUDRUUBUFFULRBRFBFFFBFRBL', 21, 8, 77),
];

/// `U R F D L B` order, the same layout the native core uses.
const String kSolvedFacelets =
    'UUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBB';

/// The solved state with one sticker repainted, so the colour census no longer
/// balances. A validator that accepts this is not validating anything.
const String kIllegalFacelets =
    'UUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBU';

class SelfTestCheck {
  const SelfTestCheck(this.label, this.passed, this.detail);

  final String label;
  final bool passed;
  final String detail;
}

class NativeSelfTestResult {
  const NativeSelfTestResult({
    required this.checks,
    required this.log,
    required this.kociembaMicros,
    required this.cfopMicros,
    required this.coldStartMicros,
  });

  final List<SelfTestCheck> checks;

  /// One `PASS|FAIL | label | detail` line per check, mirrored to logcat so a
  /// device run can be inspected over adb without looking at the screen.
  final String log;

  final int kociembaMicros;
  final int cfopMicros;

  /// First solver call on a fresh process, which also builds the pruning
  /// tables. Orders of magnitude slower than the rest; the gap is what the
  /// app has to hide behind a warm-up.
  final int coldStartMicros;

  bool get allPassed => checks.every((c) => c.passed);

  int get failureCount => checks.where((c) => !c.passed).length;
}

/// Runs the on-device acceptance test for `librubik_core.so`.
///
/// Deliberately exercises *scrambled* states: the solved state takes a trivial
/// branch in both solvers and would pass even if the pruning tables were
/// completely wrong. Yields to the event loop between vectors so a slow device
/// can still paint progress instead of tripping the watchdog.
Future<NativeSelfTestResult> runNativeSelfTest({
  void Function(int done, int total)? onProgress,
}) async {
  final engine = RubikFfiBridge.instance;
  final checks = <SelfTestCheck>[];
  final log = StringBuffer();

  void record(String label, bool passed, String detail) {
    checks.add(SelfTestCheck(label, passed, detail));
    log.writeln('${passed ? 'PASS' : 'FAIL'} | $label | $detail');
  }

  record(
    '原生库 librubik_core.so',
    engine.isLoaded,
    engine.isLoaded ? '已加载，12 个 FFI 符号解析成功' : (engine.loadError ?? '加载失败'),
  );
  record(
    '管线句柄 init_cube_pipeline',
    engine.isPipelineInitialized,
    engine.isPipelineInitialized ? '上下文已创建' : (engine.pipelineError ?? '未初始化'),
  );

  final solvedError = engine.validate(kSolvedFacelets);
  record('validate(已还原)', solvedError == null,
      solvedError ?? '通过颜色计数与守恒校验');

  final illegalError = engine.validate(kIllegalFacelets);
  record(
    'validate(非法态必须拒绝)',
    illegalError != null,
    illegalError ?? '**接受了非法状态，校验器形同虚设**',
  );

  final solvedSolution = engine.solveKociemba(kSolvedFacelets);
  record('solve(已还原)', solvedSolution == 'SOLVED',
      solvedSolution == 'SOLVED' ? '正确识别' : solvedSolution);

  if (kDeviceVectors.isEmpty) {
    return NativeSelfTestResult(
      checks: checks,
      log: log.toString(),
      kociembaMicros: 0,
      cfopMicros: 0,
      coldStartMicros: 0,
    );
  }

  // Cold start: the first real solve also builds both pruning tables, so it is
  // timed on its own instead of polluting the per-vector average. Yield first
  // so whoever is showing progress gets to paint before the thread blocks.
  await Future<void>.delayed(const Duration(milliseconds: 64));
  final coldWatch = Stopwatch()..start();
  final firstKociemba = engine.solveKociemba(kDeviceVectors.first.facelets);
  coldWatch.stop();
  final coldStartMicros = coldWatch.elapsedMicroseconds;
  record('冷启动首次求解（含建表）', firstKociemba.isNotEmpty,
      '${(coldStartMicros / 1000).toStringAsFixed(0)} ms');

  var kociembaMicros = 0;
  var cfopMicros = 0;
  var matches = 0;
  var lengthMismatches = <String>[];
  var cfopProblems = <String>[];
  var structureProblems = <String>[];
  final layouts = <String>[];

  for (var i = 0; i < kDeviceVectors.length; i++) {
    final v = kDeviceVectors[i];

    final kocWatch = Stopwatch()..start();
    final solution = engine.solveKociemba(v.facelets);
    kociembaMicros += kocWatch.elapsedMicroseconds;

    final cfopWatch = Stopwatch()..start();
    final cfopJson = engine.generateCfopJson(v.facelets);
    cfopMicros += cfopWatch.elapsedMicroseconds;

    final moves = _moveCount(solution);
    if (moves == v.hostKociembaLen) {
      matches++;
    } else {
      lengthMismatches.add('#$i 设备 $moves vs 主机 ${v.hostKociembaLen}'
          '${moves == null ? '（无法解析："$solution"）' : ''}');
    }

    final parsed = _inspectCfop(cfopJson);
    layouts.add('#$i stages=${parsed.stages} [${parsed.layout.join(', ')}]');
    if (parsed.stages != v.hostCfopStages) {
      cfopProblems.add('#$i 阶段数 设备 ${parsed.stages} vs 主机 ${v.hostCfopStages}');
    }
    if (parsed.missingFormula > 0) {
      cfopProblems.add('#$i 有 ${parsed.missingFormula} 个阶段 formula 为空');
    }
    if (parsed.missingAlgorithms > 0) {
      structureProblems.add('#$i 有 ${parsed.missingAlgorithms} 个阶段未给出算法名');
    }
    if (parsed.missingText > 0) {
      structureProblems.add('#$i 有 ${parsed.missingText} 个阶段的讲解文本为空');
    }

    onProgress?.call(i + 1, kDeviceVectors.length);
    await Future<void>.delayed(Duration.zero);
  }

  final n = kDeviceVectors.length;
  log.writeln('--- CFOP 阶段分解（逐行对比 tools/native_tests 的 gen_vectors 输出）---');
  for (final line in layouts) {
    log.writeln(line);
  }
  record(
    'Kociemba 解长度与主机一致',
    lengthMismatches.isEmpty,
    lengthMismatches.isEmpty
        ? '$matches/$n 一致，平均 ${(kociembaMicros / 1000 / n).toStringAsFixed(0)} ms'
        : lengthMismatches.join('；'),
  );
  record(
    'CFOP 阶段划分与主机一致',
    cfopProblems.isEmpty,
    cfopProblems.isEmpty
        ? '$n/$n 一致，平均 ${(cfopMicros / 1000 / n).toStringAsFixed(0)} ms'
        : cfopProblems.join('；'),
  );
  record(
    'CFOP 教学字段完整（算法名 / 讲解）',
    structureProblems.isEmpty,
    structureProblems.isEmpty ? '每阶段均带公式名与讲解' : structureProblems.join('；'),
  );

  await _runVisionSelfTest(engine, record, log);

  return NativeSelfTestResult(
    checks: checks,
    log: log.toString(),
    kociembaMicros: kociembaMicros,
    cfopMicros: cfopMicros,
    coldStartMicros: coldStartMicros,
  );
}

// ---------------------------------------------------------------------------
// Vision self test
// ---------------------------------------------------------------------------

/// A synthetic I420 frame: a 3x3 grid of solid stickers inside the guide box
/// and black outside it, which is what the camera sees when a cube is held over
/// a dark table.
///
/// This is the only way to exercise the camera path without a camera. It checks
/// the YUV unpacking, the sampling geometry, the colour classification, the
/// white balance bootstrap and the six-face stitch, all on the device's own
/// ARM build - the half of the engine that a host test can only approximate.
class _SyntheticFrame {
  _SyntheticFrame(this.width, this.height)
      : y = Uint8List(width * height),
        u = Uint8List((width ~/ 2) * (height ~/ 2)),
        v = Uint8List((width ~/ 2) * (height ~/ 2));

  final int width;
  final int height;
  final Uint8List y;
  final Uint8List u;
  final Uint8List v;

  int get yStride => width;
  int get uvStride => width ~/ 2;

  /// Sticker colours, close to but not equal to the native anchors so the test
  /// measures classification rather than a lookup.
  static const List<List<int>> _stickerRgb = <List<int>>[
    <int>[250, 250, 250], // white
    <int>[210, 40, 50], // red
    <int>[40, 175, 80], // green
    <int>[250, 220, 60], // yellow
    <int>[235, 150, 40], // orange
    <int>[35, 95, 195], // blue
  ];

  /// Paints nine sticker colours into a centred 3x3 grid.
  ///
  /// The geometry mirrors `kGuideSideFraction` on the Dart side and
  /// `sampleFaceGrid`'s default on the native side; if those ever drift apart
  /// this test starts reading the black background and fails loudly.
  void fill(List<int> cells) {
    final side = math.min(width, height) * 0.72;
    final left = (width - side) / 2;
    final top = (height - side) / 2;
    final cell = side / 3;

    for (var py = 0; py < height; py++) {
      for (var px = 0; px < width; px++) {
        var yy = 16, uu = 128, vv = 128; // black

        final fx = px - left;
        final fy = py - top;
        if (fx >= 0 && fy >= 0 && fx < side && fy < side) {
          final gx = math.min(2, (fx / cell).floor());
          final gy = math.min(2, (fy / cell).floor());
          final rgb = _stickerRgb[cells[gy * 3 + gx]];
          yy = (0.257 * rgb[0] + 0.504 * rgb[1] + 0.098 * rgb[2] + 16)
              .round()
              .clamp(0, 255);
          uu = (-0.148 * rgb[0] - 0.291 * rgb[1] + 0.439 * rgb[2] + 128)
              .round()
              .clamp(0, 255);
          vv = (0.439 * rgb[0] - 0.368 * rgb[1] - 0.071 * rgb[2] + 128)
              .round()
              .clamp(0, 255);
        }

        y[py * width + px] = yy;
        if (py.isEven && px.isEven) {
          final idx = (py ~/ 2) * uvStride + px ~/ 2;
          u[idx] = uu;
          v[idx] = vv;
        }
      }
    }
  }
}

const Map<String, int> _kColorIndexByFacelet = <String, int>{
  'U': 0,
  'R': 1,
  'F': 2,
  'D': 3,
  'L': 4,
  'B': 5,
};

/// Drives the whole camera path with synthetic frames and checks that six
/// scanned faces come back out as a solvable cube.
Future<void> _runVisionSelfTest(
  RubikFfiBridge engine,
  void Function(String label, bool passed, String detail) record,
  StringBuffer log,
) async {
  final facelets = kDeviceVectors.first.facelets;
  final frame = _SyntheticFrame(240, 240);
  const framesPerFace = 9; // one more than the vote window

  engine.resetScanner();

  for (var face = 0; face < 6; face++) {
    final cells = <int>[];
    for (var k = 0; k < 9; k++) {
      cells.add(_kColorIndexByFacelet[facelets[face * 9 + k]]!);
    }
    frame.fill(cells);

    for (var f = 0; f < framesPerFace; f++) {
      engine.processFrameYuv(
        yPlane: frame.y,
        yStride: frame.yStride,
        yPixelStride: 1,
        uPlane: frame.u,
        uStride: frame.uvStride,
        uPixelStride: 1,
        vPlane: frame.v,
        vStride: frame.uvStride,
        vPixelStride: 1,
        width: frame.width,
        height: frame.height,
        rotationDegrees: 0,
      );
    }

    await Future<void>.delayed(Duration.zero);
  }

  final lockedFaces = engine.getScannedFacesCount();
  record(
    '视觉扫描：六面识别',
    lockedFaces == 6,
    '$lockedFaces/6 面通过多帧表决',
  );

  final assembled = engine.getScannedCubeString();
  if (assembled == null) {
    record(
      '视觉扫描：六面拼合',
      false,
      '六面已识别但无法拼成合法状态（朝向对齐失败）',
    );
    return;
  }

  log.writeln('识别拼合结果: $assembled');
  log.writeln('原始打乱状态: $facelets');

  final validationError = engine.validate(assembled);
  record(
    '视觉扫描：拼合结果可解',
    validationError == null,
    validationError ?? '通过校验，可交给求解器',
  );
}


/// Number of moves in a native solution string, or `null` when it cannot be
/// parsed. `SOLVED` and `ERROR:` replies are not move lists.
int? _moveCount(String solution) {
  final trimmed = solution.trim();
  if (trimmed.isEmpty || trimmed == 'SOLVED' || trimmed.startsWith('ERROR')) {
    return null;
  }
  return trimmed.split(RegExp(r'\s+')).length;
}

class _CfopInspection {
  int stages = 0;
  int missingFormula = 0;
  int missingAlgorithms = 0;
  int missingText = 0;

  /// `name:moveCount` per stage, in order, for diffing against the host.
  final List<String> layout = <String>[];
}

/// First stage id that is part of the last layer. Cross and the four F2L slots
/// are raw searches with no formula to name; only the last layer stages are
/// supposed to carry named algorithms.
const int _kFirstLastLayerStageId = 5;

_CfopInspection _inspectCfop(String json) {
  final result = _CfopInspection();
  dynamic decoded;
  try {
    decoded = jsonDecode(json);
  } catch (_) {
    return result;
  }
  if (decoded is! List) return result;

  result.stages = decoded.length;
  for (final dynamic entry in decoded) {
    if (entry is! Map) {
      result.missingFormula++;
      continue;
    }
    final formula = entry['formula'];
    final formulaOk = formula is String && formula.trim().isNotEmpty;
    if (!formulaOk) result.missingFormula++;

    final stageId = entry['stageId'];
    final isLastLayer = stageId is int && stageId >= _kFirstLastLayerStageId;

    final algorithms = entry['algorithms'];
    if (isLastLayer && (algorithms is! List || algorithms.isEmpty)) {
      result.missingAlgorithms++;
    }

    final hint = entry['visualHint'];
    final explanation = entry['explanation'];
    final hasHint = hint is String && hint.trim().isNotEmpty;
    final hasExplanation = explanation is String && explanation.trim().isNotEmpty;
    if (!hasHint || !hasExplanation) result.missingText++;

    final name = entry['stageName'];
    final label = name is String ? name : '?';
    final stageTier = entry['stageTier'];
    final tierSuffix = stageTier is int ? '/t$stageTier' : '';
    result.layout.add(
        '$label:${_moveCount(formulaOk ? formula : '') ?? 0}$tierSuffix');
  }
  return result;
}
