#pragma once
#include "cube_model.hpp"
#include "move_engine.hpp"

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <string>
#include <vector>

namespace rubik {

// ---------------------------------------------------------------------------
// Coordinates
// ---------------------------------------------------------------------------

/// 3^7 = 2187 twists of the first seven corners; the eighth is implied by the
/// twist parity invariant.
inline int twistCoord(const CubieState& s) {
    int t = 0;
    for (int i = 0; i < 7; ++i) t = 3 * t + s.co[i];
    return t;
}

/// 2^11 = 2048 flips of the first eleven edges.
inline int flipCoord(const CubieState& s) {
    int f = 0;
    for (int i = 0; i < 11; ++i) f = 2 * f + s.eo[i];
    return f;
}

/// Which of the four UD-slice edges (FR, FL, BL, BR) occupy which positions,
/// as an index in 0..494. Instead of a hand derived combinatorial formula the
/// 495 subsets of a 12 bit mask are enumerated once, which keeps the encoding
/// trivially auditable.
///
/// Masks are enumerated in *descending* order so that index 0 is the solved
/// configuration (slice edges on positions 8..11). Every coordinate in this
/// file therefore has its goal at value 0, which is what the BFS and the IDA*
/// goal tests rely on.
inline const std::array<uint16_t, 4096>& sliceMaskToIndex() {
    static const std::array<uint16_t, 4096> table = [] {
        std::array<uint16_t, 4096> t{};
        for (auto& v : t) v = 0xFFFF;
        int index = 0;
        for (int mask = 4095; mask >= 0; --mask) {
            int bits = 0;
            for (int b = 0; b < 12; ++b) bits += (mask >> b) & 1;
            if (bits == 4) t[mask] = (uint16_t)index++;
        }
        return t;
    }();
    return table;
}

inline const std::array<uint16_t, 495>& sliceIndexToMask() {
    static const std::array<uint16_t, 495> table = [] {
        std::array<uint16_t, 495> t{};
        int index = 0;
        for (int mask = 4095; mask >= 0; --mask) {
            int bits = 0;
            for (int b = 0; b < 12; ++b) bits += (mask >> b) & 1;
            if (bits == 4) t[index++] = (uint16_t)mask;
        }
        return t;
    }();
    return table;
}

inline int sliceCoord(const CubieState& s) {
    int mask = 0;
    for (int i = 0; i < 12; ++i) {
        if (s.ep[i] >= FR) mask |= 1 << i;
    }
    return sliceMaskToIndex()[mask];
}

/// Lexicographic rank of a permutation (Lehmer code), 0..n!-1.
inline int permRank(const uint8_t* p, int n) {
    int rank = 0;
    for (int i = 0; i < n; ++i) {
        int smaller = 0;
        for (int j = i + 1; j < n; ++j) {
            if (p[j] < p[i]) smaller++;
        }
        rank = rank * (n - i) + smaller;
    }
    return rank;
}

inline void permUnrank(int rank, uint8_t* p, int n) {
    static const int fact[13] = { 1, 1, 2, 6, 24, 120, 720, 5040, 40320,
                                  362880, 3628800, 39916800, 479001600 };
    uint8_t avail[12];
    for (int i = 0; i < n; ++i) avail[i] = (uint8_t)i;
    for (int i = 0; i < n; ++i) {
        const int f = fact[n - 1 - i];
        const int idx = rank / f;
        rank -= idx * f;
        p[i] = avail[idx];
        for (int j = idx; j < n - 1; ++j) avail[j] = avail[j + 1];
    }
}

/// Permutation of the four slice edges among the four slice positions (0..23).
inline int slicePermCoord(const CubieState& s) {
    uint8_t p[4] = {
        (uint8_t)(s.ep[8] - FR), (uint8_t)(s.ep[9] - FR),
        (uint8_t)(s.ep[10] - FR), (uint8_t)(s.ep[11] - FR)
    };
    return permRank(p, 4);
}

/// Permutation of the eight corners (0..40319).
inline int cornerPermCoord(const CubieState& s) {
    uint8_t p[8];
    for (int i = 0; i < 8; ++i) p[i] = (uint8_t)s.cp[i];
    return permRank(p, 8);
}

/// Permutation of the eight non-slice edges over the first eight positions.
inline int edgePermCoord(const CubieState& s) {
    uint8_t p[8];
    for (int i = 0; i < 8; ++i) p[i] = (uint8_t)s.ep[i];
    return permRank(p, 8);
}

/// True when the state already lies in the phase 2 subgroup, i.e. every U/D
/// sticker faces up or down and the slice edges sit in the slice.
inline bool inPhase2Subgroup(const CubieState& s) {
    return twistCoord(s) == 0 && flipCoord(s) == 0 && sliceCoord(s) == 0;
}

// ---------------------------------------------------------------------------
// Engine
// ---------------------------------------------------------------------------

/// Two phase (Kociemba) solver.
///
/// Phase 1 drives the cube into the subgroup generated by
/// <U, D, R2, F2, L2, B2> using the (twist, slice) and (flip, slice) pruning
/// tables; phase 2 finishes inside that subgroup using the (corner perm, slice
/// perm) and (edge perm, slice perm) tables.
class KociembaEngine {
public:
    static KociembaEngine& instance() {
        static KociembaEngine engine;
        return engine;
    }

    /// Number of moves of the last phase-1/phase-2 split, for diagnostics.
    int lastPhase1Length() const { return lastPhase1Length_; }
    int lastPhase2Length() const { return lastPhase2Length_; }

    /// Builds the move and pruning tables. Costs a few hundred milliseconds on
    /// a phone, so it happens once, on the first solve.
    void ensureTables() {
        if (ready_) return;
        buildTables();
        ready_ = true;
    }

    bool tablesReady() const { return ready_; }

    /// True when every pruning entry received a real distance during the
    /// backwards BFS. An unset entry would silently cripple the search, so the
    /// host tests assert this explicitly.
    bool pruningTablesComplete() const {
        if (!ready_) return false;
        const auto allSet = [](const std::vector<uint8_t>& v) {
            for (uint8_t b : v) {
                if (b == 0xFF) return false;
            }
            return !v.empty();
        };
        return allSet(twistSlice_) && allSet(flipSlice_) &&
               allSet(cpSlicePerm_) && allSet(epSlicePerm_);
    }

    /// Total size of the tables in bytes, useful for budgeting on device.
    size_t tableBytes() const {
        return (twistMove_.size() + flipMove_.size() + sliceMove_.size() +
                cpMove_.size() + epMove_.size() + slicePermMove_.size()) * sizeof(uint16_t) +
               twistSlice_.size() + flipSlice_.size() +
               cpSlicePerm_.size() + epSlicePerm_.size();
    }

    /// Optimal-ish two phase solution for `state`.
    ///
    /// `maxDepth` is the *preferred* upper bound for the total length and
    /// `budgetSeconds` the wall clock budget. When no solution fits inside
    /// `maxDepth` the search is repeated without that bound, because refusing
    /// to answer a solvable cube would be worse than answering with 23 moves.
    /// An empty result means the cube was already solved.
    std::vector<int> solve(const CubieState& state, int maxDepth = 22,
                           double budgetSeconds = 2.5) {
        ensureTables();
        if (CubeModel::isSolved(state)) return {};

        std::vector<int> best = searchBest(state, maxDepth, budgetSeconds);
        if (best.empty()) {
            // `maxDepth` is a preference, not a guarantee: some states simply
            // do not have a <= maxDepth split between the two phases. Retry
            // without the bound rather than reporting a solvable cube as
            // unsolvable.
            best = searchBest(state, 0, 2.0);
        }
        return best;
    }

    /// Convenience wrapper matching the original FFI contract.
    static std::string solveFacelets(const std::string& facelets, int maxDepth = 22) {
        std::string err;
        CubieState state{};
        if (!CubeModel::faceletsToCubie(facelets, state, err)) {
            return "ERROR: " + err;
        }
        if (!CubeModel::validate(facelets, err)) {
            return "ERROR: " + err;
        }
        if (CubeModel::isSolved(state)) return "SOLVED";
        const std::vector<int> moves = instance().solve(state, maxDepth);
        if (moves.empty()) return "ERROR: no solution found.";
        return sequenceToString(moves);
    }

private:
    KociembaEngine() = default;

    static constexpr int OPPOSITE_FACE[6] = { 3, 4, 5, 0, 1, 2 };

    /// The ten moves that keep the cube inside the phase 2 subgroup.
    static const std::array<int, 10>& phase2Moves() {
        static const std::array<int, 10> m = {
            0 * 3 + 0, 0 * 3 + 1, 0 * 3 + 2,   // U, U2, U'
            3 * 3 + 0, 3 * 3 + 1, 3 * 3 + 2,   // D, D2, D'
            1 * 3 + 1, 2 * 3 + 1, 4 * 3 + 1, 5 * 3 + 1   // R2, F2, L2, B2
        };
        return m;
    }

    std::vector<int> searchBest(const CubieState& state, int maxTotalLen,
                                double budgetSeconds) {
        const auto deadline = std::chrono::steady_clock::now() +
            std::chrono::duration_cast<std::chrono::steady_clock::duration>(
                std::chrono::duration<double>(budgetSeconds));
        deadline_ = deadline;

        const int twist = twistCoord(state);
        const int flip = flipCoord(state);
        const int slice = sliceCoord(state);

        std::vector<int> best;
        int bestLen = 1 << 30;
        const int h1 = std::max(twistSlice_[twist * 495 + slice],
                                flipSlice_[flip * 495 + slice]);

        for (int d1 = h1; d1 <= 12; ++d1) {
            if (maxTotalLen > 0 && d1 >= maxTotalLen) break;
            limit_ = d1;
            path_.clear();
            solutions_.clear();
            timedOut_ = false;
            nodes_ = 0;
            dfs1(twist, flip, slice, 0, -1);
            if (timedOut_ && solutions_.empty()) break;

            for (const std::vector<int>& head : solutions_) {
                const CubieState after1 = applySequence(state, head);
                // Phase 1 only drives the cube into <U, D, R2, F2, L2, B2>;
                // the remaining corner/edge permutation is phase 2's job. Even
                // when the state already sits in the subgroup phase 2 runs and
                // simply returns an empty tail when nothing is left to do.
                std::vector<int> tail;
                const int phase2Cap = (maxTotalLen > 0)
                                          ? std::min(18, maxTotalLen - d1)
                                          : 18;
                if (phase2Cap < 0) continue;
                if (!solvePhase2(after1, phase2Cap, tail)) continue;
                const int total = (int)(head.size() + tail.size());
                if (total < bestLen) {
                    bestLen = total;
                    best = head;
                    best.insert(best.end(), tail.begin(), tail.end());
                    lastPhase1Length_ = (int)head.size();
                    lastPhase2Length_ = (int)tail.size();
                }
            }

            // A short phase 1 plus a near optimal phase 2 already lands around
            // 20 moves; deeper phase 1 only buys a move or two.
            if (!best.empty() && bestLen <= d1 + 9) break;
            if (std::chrono::steady_clock::now() > deadline) break;
        }
        return best;
    }

    void buildTables() {
        // ---- phase 1 move tables -------------------------------------------
        twistMove_.assign(2187 * 18, 0);
        flipMove_.assign(2048 * 18, 0);
        sliceMove_.assign(495 * 18, 0);

        buildTwistMove();
        buildFlipMove();
        buildSliceMove();

        // ---- phase 2 move tables -------------------------------------------
        cpMove_.assign(40320 * 10, 0);
        epMove_.assign(40320 * 10, 0);
        slicePermMove_.assign(24 * 10, 0);
        buildPhase2MoveTables();

        // ---- pruning tables -------------------------------------------------
        buildPhase1Pruning();
        buildPhase2Pruning();
    }

    void buildTwistMove() {
        for (int coord = 0; coord < 2187; ++coord) {
            CubieState s = CubeModel::solvedState();
            int rest = coord;
            int sum = 0;
            for (int i = 6; i >= 0; --i) {
                s.co[i] = (int8_t)(rest % 3);
                sum += s.co[i];
                rest /= 3;
            }
            s.co[7] = (int8_t)((3 - sum % 3) % 3);
            for (int m = 0; m < 18; ++m) {
                twistMove_[coord * 18 + m] = (uint16_t)twistCoord(applyMove(s, m));
            }
        }
    }

    void buildFlipMove() {
        for (int coord = 0; coord < 2048; ++coord) {
            CubieState s = CubeModel::solvedState();
            int rest = coord;
            int sum = 0;
            for (int i = 10; i >= 0; --i) {
                s.eo[i] = (int8_t)(rest % 2);
                sum += s.eo[i];
                rest /= 2;
            }
            s.eo[11] = (int8_t)(sum % 2);
            for (int m = 0; m < 18; ++m) {
                flipMove_[coord * 18 + m] = (uint16_t)flipCoord(applyMove(s, m));
            }
        }
    }

    void buildSliceMove() {
        for (int coord = 0; coord < 495; ++coord) {
            CubieState s = CubeModel::solvedState();
            const int mask = sliceIndexToMask()[coord];
            // Slice pieces fill the masked positions, everything else takes the
            // remaining positions in order. The coordinate only tracks which
            // positions hold slice pieces, so any filling is equivalent.
            int slicePiece = FR;
            int otherPiece = UR;
            for (int i = 0; i < 12; ++i) {
                if (mask & (1 << i)) {
                    s.ep[i] = (int8_t)slicePiece++;
                } else {
                    while (otherPiece >= FR) otherPiece++;
                    s.ep[i] = (int8_t)otherPiece++;
                }
            }
            for (int m = 0; m < 18; ++m) {
                sliceMove_[coord * 18 + m] = (uint16_t)sliceCoord(applyMove(s, m));
            }
        }
    }

    void buildPhase2MoveTables() {
        const std::array<int, 10>& moves = phase2Moves();

        uint8_t perm[8];
        for (int coord = 0; coord < 40320; ++coord) {
            permUnrank(coord, perm, 8);

            CubieState c = CubeModel::solvedState();
            for (int i = 0; i < 8; ++i) c.cp[i] = (int8_t)perm[i];
            for (int k = 0; k < 10; ++k) {
                cpMove_[coord * 10 + k] = (uint16_t)cornerPermCoord(applyMove(c, moves[k]));
            }

            CubieState e = CubeModel::solvedState();
            for (int i = 0; i < 8; ++i) e.ep[i] = (int8_t)perm[i];
            for (int k = 0; k < 10; ++k) {
                const CubieState next = applyMove(e, moves[k]);
                epMove_[coord * 10 + k] = (uint16_t)edgePermCoord(next);
            }
        }

        uint8_t sp[4];
        for (int coord = 0; coord < 24; ++coord) {
            permUnrank(coord, sp, 4);
            CubieState s = CubeModel::solvedState();
            for (int i = 0; i < 4; ++i) s.ep[8 + i] = (int8_t)(FR + sp[i]);
            for (int k = 0; k < 10; ++k) {
                slicePermMove_[coord * 10 + k] = (uint16_t)slicePermCoord(applyMove(s, moves[k]));
            }
        }
    }

    /// Breadth first distances over a product coordinate space.
    ///
    /// `sizeA * sizeB` is at most ~1.1M entries, so a plain byte array plus a
    /// frontier queue stays comfortably small.
    template <typename StepFn, typename GoalFn>
    static void bfsProduct(int sizeA, int sizeB, int branching, StepFn step,
                           GoalFn isGoal, std::vector<uint8_t>& dist) {
        const int total = sizeA * sizeB;
        dist.assign(total, (uint8_t)0xFF);

        std::vector<uint32_t> frontier;
        std::vector<uint32_t> next;
        dist[0] = 0;
        frontier.push_back(0);

        uint8_t depth = 0;
        while (!frontier.empty()) {
            next.clear();
            ++depth;
            for (uint32_t state : frontier) {
                const int a = (int)(state / sizeB);
                const int b = (int)(state % sizeB);
                for (int m = 0; m < branching; ++m) {
                    const int na = step.first(a, m);
                    const int nb = step.second(b, m);
                    const uint32_t idx = (uint32_t)(na * sizeB + nb);
                    if (dist[idx] != 0xFF) continue;
                    dist[idx] = depth;
                    next.push_back(idx);
                }
            }
            frontier.swap(next);
            if (frontier.size() > (size_t)total) break;
        }
        (void)isGoal;
    }

    void buildPhase1Pruning() {
        twistSlice_.resize(2187 * 495);
        flipSlice_.resize(2048 * 495);

        const auto twistStep = [this](int a, int m) { return (int)twistMove_[a * 18 + m]; };
        const auto flipStep = [this](int a, int m) { return (int)flipMove_[a * 18 + m]; };
        const auto sliceStep = [this](int a, int m) { return (int)sliceMove_[a * 18 + m]; };

        bfsProduct(2187, 495, 18,
                   std::make_pair(twistStep, sliceStep), nullptr, twistSlice_);
        bfsProduct(2048, 495, 18,
                   std::make_pair(flipStep, sliceStep), nullptr, flipSlice_);
    }

    void buildPhase2Pruning() {
        cpSlicePerm_.resize(40320 * 24);
        epSlicePerm_.resize(40320 * 24);

        const auto cpStep = [this](int a, int m) { return (int)cpMove_[a * 10 + m]; };
        const auto epStep = [this](int a, int m) { return (int)epMove_[a * 10 + m]; };
        const auto spStep = [this](int a, int m) { return (int)slicePermMove_[a * 10 + m]; };

        bfsProduct(40320, 24, 10,
                   std::make_pair(cpStep, spStep), nullptr, cpSlicePerm_);
        bfsProduct(40320, 24, 10,
                   std::make_pair(epStep, spStep), nullptr, epSlicePerm_);
    }

    bool aborted() {
        if (solutions_.size() >= (size_t)maxSolutions_) return true;
        if (timedOut_) return true;
        if ((++nodes_ & 0xFFFF) == 0 &&
            std::chrono::steady_clock::now() > deadline_) {
            timedOut_ = true;
            return true;
        }
        return false;
    }

    void dfs1(int twist, int flip, int slice, int depth, int lastFace) {
        if (aborted()) return;

        const int h = std::max(twistSlice_[twist * 495 + slice],
                               flipSlice_[flip * 495 + slice]);
        if (depth + h > limit_) return;

        if (twist == 0 && flip == 0 && slice == 0) {
            solutions_.push_back(path_);
            return;
        }
        if (depth == limit_) return;

        for (int face = 0; face < 6; ++face) {
            if (face == lastFace) continue;
            // U/D, R/L and F/B commute, so only keep one of the two orders.
            if (lastFace >= 0 && face == OPPOSITE_FACE[lastFace] && face > lastFace) continue;
            for (int amount = 0; amount < 3; ++amount) {
                const int m = face * 3 + amount;
                path_.push_back(m);
                dfs1((int)twistMove_[twist * 18 + m],
                     (int)flipMove_[flip * 18 + m],
                     (int)sliceMove_[slice * 18 + m],
                     depth + 1, face);
                path_.pop_back();
                if (aborted()) return;
            }
        }
    }

    /// Optimal phase 2 completion of `state`, bounded by `maxLen` moves.
    bool solvePhase2(const CubieState& state, int maxLen, std::vector<int>& out) {
        const int cp = cornerPermCoord(state);
        const int ep = edgePermCoord(state);
        const int sp = slicePermCoord(state);
        const int h = std::max(cpSlicePerm_[cp * 24 + sp], epSlicePerm_[ep * 24 + sp]);

        for (int limit = h; limit <= maxLen; ++limit) {
            p2Path_.clear();
            if (dfs2(cp, ep, sp, 0, limit, -1)) {
                out = p2Path_;
                return true;
            }
        }
        return false;
    }

    bool dfs2(int cp, int ep, int sp, int depth, int limit, int lastFace) {
        const int h = std::max(cpSlicePerm_[cp * 24 + sp], epSlicePerm_[ep * 24 + sp]);
        if (depth + h > limit) return false;
        if (cp == 0 && ep == 0 && sp == 0) return true;
        if (depth == limit) return false;

        const std::array<int, 10>& moves = phase2Moves();
        for (int k = 0; k < 10; ++k) {
            const int face = moves[k] / 3;
            if (face == lastFace) continue;
            // R2/L2 and F2/B2 commute, so keep a single canonical order.
            if (lastFace >= 0 && face == OPPOSITE_FACE[lastFace] && face > lastFace) continue;
            p2Path_.push_back(moves[k]);
            if (dfs2((int)cpMove_[cp * 10 + k],
                     (int)epMove_[ep * 10 + k],
                     (int)slicePermMove_[sp * 10 + k],
                     depth + 1, limit, face)) {
                return true;
            }
            p2Path_.pop_back();
        }
        return false;
    }

    bool ready_ = false;

    std::vector<uint16_t> twistMove_;
    std::vector<uint16_t> flipMove_;
    std::vector<uint16_t> sliceMove_;
    std::vector<uint16_t> cpMove_;
    std::vector<uint16_t> epMove_;
    std::vector<uint16_t> slicePermMove_;

    std::vector<uint8_t> twistSlice_;
    std::vector<uint8_t> flipSlice_;
    std::vector<uint8_t> cpSlicePerm_;
    std::vector<uint8_t> epSlicePerm_;

    int limit_ = 0;
    int maxSolutions_ = 160;
    int nodes_ = 0;
    bool timedOut_ = false;
    std::chrono::steady_clock::time_point deadline_{};

    std::vector<int> path_;
    std::vector<int> p2Path_;
    std::vector<std::vector<int>> solutions_;

    int lastPhase1Length_ = 0;
    int lastPhase2Length_ = 0;
};

/// Backwards compatible entry point used by the FFI layer.
class KociembaSolver {
public:
    static std::string solve(const std::string& facelets, int max_depth = 22) {
        return KociembaEngine::solveFacelets(facelets, max_depth);
    }
};

}  // namespace rubik
