// Device self-test vector generator.
//
// Emits a small table of scrambled cube states in Dart syntax, together with
// the solver results measured on the host. The table is pasted into
// lib/core/native_bridge/native_selftest.dart so the phone can check itself:
//
//  * every vector must validate, solve and produce a CFOP guide on device
//  * the solution length produced on the phone (arm64) is compared with the
//    length produced here (x86_64), which catches the kind of bug that only
//    shows up on a different target - undefined behaviour, integer overflow,
//    uninitialised reads, a stale pruning table layout.
//
// The states are fixed rather than random so the comparison stays meaningful
// across machines and toolchains.
//
// Build and run with tools/native_tests/probe.bat gen_vectors.cpp
#include "cube_model.hpp"
#include "cfop_pipeline.hpp"
#include "kociemba_solver.hpp"
#include "move_engine.hpp"

#include <cstdio>
#include <string>
#include <vector>

using namespace rubik;

struct Rng {
    uint32_t s;
    explicit Rng(uint32_t seed) : s(seed) {}
    uint32_t next() {
        s = s * 1664525u + 1013904223u;
        return s;
    }
    int below(int n) { return (int)(next() % (uint32_t)n); }
};

static std::vector<int> randomScramble(Rng& rng, int length) {
    std::vector<int> moves;
    int lastFace = -1;
    while ((int)moves.size() < length) {
        const int face = rng.below(6);
        if (face == lastFace) continue;
        lastFace = face;
        moves.push_back(face * 3 + rng.below(3));
    }
    return moves;
}

int main() {
    // Warm the tables up first so the printed timings are solver time only.
    KociembaEngine::instance().ensureTables();
    CfopEngine::instance().ensureTables();

    constexpr int kCount = 8;
    Rng rng(20260928u);

    std::printf("// Generated by tools/native_tests/gen_vectors.cpp - do not edit.\n");
    std::printf("// %d scrambled states with their host (x86_64) solver results.\n",
                kCount);
    std::printf("const List<DeviceVector> kDeviceVectors = <DeviceVector>[\n");

    for (int i = 0; i < kCount; ++i) {
        const std::vector<int> scramble = randomScramble(rng, 25);
        const CubieState scrambled = applySequence(CubeModel::solvedState(), scramble);
        const std::string facelets = CubeModel::cubieToFacelets(scrambled);

        const std::vector<int> koc = KociembaEngine::instance().solve(scrambled, 0, 2.0);
        const int kocLen = (int)koc.size();

        const std::vector<CfopEngine::Stage> stages = CfopEngine::instance().solve(scrambled);
        int cfopTotal = 0;
        for (const CfopEngine::Stage& s : stages) cfopTotal += (int)s.moves.size();

        // Sanity: a vector that does not solve on the host is useless as a
        // device reference, so refuse to emit it.
        const CubieState afterKoc = applySequence(scrambled, koc);
        const bool kocOk = CubeModel::isSolved(afterKoc);

        std::printf("  DeviceVector('%s', %d, %d, %d),%s\n",
                    facelets.c_str(), kocLen, (int)stages.size(), cfopTotal,
                    kocOk ? "" : "  // <-- HOST FAILED TO SOLVE");

        // Per-stage breakdown, in the same shape the device self test prints
        // to logcat, so the two can be diffed line by line.
        std::printf("//   #%d stages=%d [", i, (int)stages.size());
        for (size_t k = 0; k < stages.size(); ++k) {
            std::printf("%s%s:%d/t%d", k == 0 ? "" : ", ",
                        stages[k].name.c_str(), (int)stages[k].moves.size(),
                        stages[k].tier);
        }
        std::printf("]\n");

        if (!kocOk) {
            std::fprintf(stderr, "vector %d does not solve on the host\n", i);
            return 1;
        }
    }

    std::printf("];\n");
    return 0;
}
